[build-system]
requires = ["setuptools>=69", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-lens"                  # distribution name on PyPI
version = "0.1.0"
description = "Chess board & piece detection tools"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy==1.26.4",
  "ml_dtypes==0.5.0",
  "opencv-python==4.11.0.86",
  "torch==2.9.1",
  "torchvision==0.24.1",
  "matplotlib==3.10.8",
  "dotenv==0.9.9",
  "chess==1.11.2",
  "CairoSVG==2.8.2",
  "contourpy==1.3.3",
  "pillow==12.1.0",
  "tqdm==4.67.1",
  "scipy==1.16.3",
  "scikit-learn==1.8.0",
  "onnx==1.20.0",
  "onnxruntime==1.23.2",
]

# Optional: create CLI commands (map command -> module:function)
#[project.scripts]
#chesslens-yolo = "PieceDetection.main_yolo:main"   # ensure a main() exists
#chesslens-board = "BoardDetection.BoardDetection:main"  # adjust to your file/function

[tool.setuptools]
package-dir = {"" = "src"}   # use the src/ layout

# Auto-find packages in src/, but only include the ones you listed
[tool.setuptools.packages.find]
where = ["src"]
include = [
  "BoardDetection*",
  "Clock_Recognition*",
  "Dataset*",
  "PieceDetection*",
  "Utils*",
  "compression*",
  "ContextAwareModels*",
  "Game*",
  "HMM*",
  "OcclusionDetection*",
  "WakeupDetection*"
]

# Package non-.py assets (png/svg etc.) inside those packages
[tool.setuptools.package-data]
BoardDetection = ["**/*.png", "**/*.svg"]
Clock_Recognition = ["**/*.png", "**/*.svg"]
Dataset = ["**/*"]
PieceDetection = ["**/*.png", "**/*.svg"]
Utils = ["**/*.png", "**/*.svg"]
