from typing import Literal
import numpy as np


def add(a: int, b: int) -> int: ...


ChessSquare = Literal[
    "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8",
    "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8",
    "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8",
    "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8",
    "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8",
    "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8",
    "g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8",
    "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8",
]


class ChessMove:
    def __init__(from_sq: ChessSquare, to_sq: ChessSquare): ...
    def __str__() -> str: ...
    def __repr__() -> str: ...


class ChessGameState:
    def __init__(fen: str | None): ...
    def __str__() -> str: ...
    def __repr__() -> str: ...

    def eval_next() -> None: ...
    def eval_prob() -> float: ...
    def get_fen() -> str: ...
    def get_timestep() -> int: ...


class GameStateFactory:
    def __init__(): ...
    def get_state(): ...


class ChessHMM:
    def __init__(max_width: int, fen: str | None): ...

    def top_t() -> int: ...
    def top_bind_t() -> int: ...

    def set_probs(timestep: int, obs_probs: np.ndarray) -> None: ...
    def bind(timestep: int) -> None: ...

    def print(timestep: int) -> str: ...
    def get_history(include_non_bound: bool = False) -> np.ndarray: ...
    def get_pgn() -> str: ...


def test_prob(obs_probs: np.ndarray) -> float: ...
